# This workflow validates all games

name: Validate Game Data

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual trigger for testing

permissions:
  contents: read

jobs:
  validate-banners:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Validate game banner images
        run: node __tests__/validate-game-banners.js
